routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::resource('rate', 'RateController');

app/Rate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Webpatser\Uuid\Uuid;

class Rate extends Model
{
    protected $fillable = [
        'birthday',
        'count',
        'base',
        'currency',
        'rate'
    ];

    protected $dates = [
        'birthday'
    ];

    protected $keyType = 'string';

    public $incrementing = false;

    /**
     *  Setup model event hooks
     */
    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model->id = (string) Uuid::generate(4);
        });
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/RateController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\RateDataTable;
use App\Fixer\Client;
use App\Http\Requests\StoreRate;
use App\Rate;
use Carbon\Carbon;
use Illuminate\Http\Request;

class RateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(RateDataTable $dt)
    {
        return $dt->render('rates.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreRate $request
     * @param  Client $client
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(StoreRate $request, Client $client)
    {
        $validated = $request->validated();

        $response  = $client->getExchangeRate(
            Carbon::createFromFormat('Y-m-d', $validated['birthday']),
            $validated['currency']
        );

        if (!$response) {
            return response()->json(['message' => $client->getError()], 500);
        }

        $rate   = $client->getRate();
        $record = Rate::where('birthday', $validated['birthday'])
            ->where('base', $rate['base'])
            ->first();

        if ($record) {
            $record->increment('count');
        } else {
            Rate::create([
                'birthday' => $validated['birthday'],
                'base'     => $rate['base'],
                'currency' => $rate['currency'],
                'rate'     => $rate['rate']
            ]);
        }

        $request->session()->flash('success', true);
        return response()->json(['message' => trans('ui.messages.thanks')], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Rate  $rate
     * @return \Illuminate\Http\Response
     */
    public function show(Rate $rate)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Rate  $rate
     * @return \Illuminate\Http\Response
     */
    public function edit(Rate $rate)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Rate  $rate
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Rate $rate)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Rate  $rate
     * @return \Illuminate\Http\Response
     */
    public function destroy(Rate $rate)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

    @if (session()->has('error'))
        <div class="alert alert-danger alert-dismissible">
            {{ session('error') }}
        </div>
    @endif

    @if (session()->has('success') && session('success', false) === true)
        <div class="alert alert-success alert-dismissible">
            {{ trans('ui.messages.thanks') }}
        </div>
    @endif

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <v-row>
        <v-col cols="6">
            <h2 class="my-5 font-weight-normal text-center">{{ trans('ui.titles.home') }}</h2>
            <p class="intro text-center">
                {{ trans('ui.titles.subtitle') }}
                <br>
                {{ trans('ui.titles.intro') }}
            </p>

            <v-form @submit.prevent="processForm">
                {{ csrf_field() }}
                <v-menu
                    v-model="menu"
                    :close-on-content-click="false"
                    :nudge-right="40"
                    transition="scale-transition"
                    offset-y
                    min-width="290px"
                >
                    <template v-slot:activator="{ on }">
                        <v-text-field
                            v-model="birthday"
                            label="{{ trans('ui.labels.birthday') }}"
                            prepend-icon="mdi-calendar-check-outline"
                            readonly
                            v-on="on"
                            :error="birthdayError"
                            :error-messages="birthdayError"
                        ></v-text-field>
                    </template>
                    <v-date-picker v-model="birthday" @input="menu = false"></v-date-picker>
                </v-menu>

                <v-select
                    v-model="currency"
                    :items="currencies"
                    :error="currencyError"
                    :error-messages="currencyError"
                    label="{{ trans('ui.labels.currency') }}"
                >
                    <template v-slot:selection="{ item, index }">
                        <v-chip v-if="index === 0">
                            <span>@{{ item }}</span>
                        </v-chip>
                        <span
                                v-if="index === 1"
                                class="grey--text caption"
                        >(+@{{ currency.length - 1 }} others)</span>
                    </template>
                </v-select>

                <input type="submit" class="btn btn-primary mt-5">
            </v-form>
        </v-col>
    </v-row>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ trans('ui.titles.meta_title') }}</title>
    <meta name="description" content="@yield('metaDescription')">
    <meta name="author" content="Jon Bowes <https://jbxonline.net>">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" href="/favicon.ico">

    <!-- Polyfills for browsers that don't support features (looking at you IE!!)-->
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{{ mix( '/css/app.css') }}">

</head>


<body>

<div id="app">
    <v-app>
        <v-navigation-drawer v-model="drawer" app>
            <v-list dense>
                <v-list-item @click="">
                    <v-list-item-action>
                        <v-icon>mdi-home</v-icon>
                    </v-list-item-action>
                    <v-list-item-content>
                        <v-list-item-title>
                            <a href="{{route('home')}}">Home</a>
                        </v-list-item-title>
                    </v-list-item-content>
                </v-list-item>
                <v-list-item @click="">
                    <v-list-item-action>
                        <v-icon>mdi-database-search</v-icon>
                    </v-list-item-action>
                    <v-list-item-content>
                        <v-list-item-title>
                            <a href="{{route('rate.index')}}">Results</a>
                        </v-list-item-title>
                    </v-list-item-content>
                </v-list-item>
            </v-list>
        </v-navigation-drawer>

        <v-app-bar app color="indigo" dark>
            <v-app-bar-nav-icon @click.stop="drawer = !drawer"></v-app-bar-nav-icon>
            <v-toolbar-title>
                <a class="navbar-brand" href="https://www.deptagency.com/" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 173 46" width="173" height="46">
                        <path d="M147.9 46h12.6V10.8H173V0h-37.6v10.8h12.5V46zm-41.5-24.9V9.9h7.2c4.6 0 6.9 1.9 6.9 5.6 0 3.7-2.3 5.6-6.9 5.6h-7.2zM93.9 46h12.6V31h7.5c11.3 0 18.8-4.9 18.8-15.5S125.2 0 114 0H93.9v46zm-43.3 0h34.3V35.7H63.2v-7.8h21.5V18H63.2v-7.7h21.7V0H50.6v46zm-38-10.7V10.7h4c8.8 0 14.3 3.2 14.3 12.3 0 9.1-5.4 12.3-14.3 12.3h-4zM0 46h16.5c15.6 0 26.9-6.2 26.9-23C43.3 6.2 32 0 16.5 0H0v46z"></path>
                    </svg>
                </a>
            </v-toolbar-title>
        </v-app-bar>

        <v-content>
            <v-container fluid fill-height>
                <v-layout justify-center>
                    @yield('content')
                </v-layout>
            </v-container>
        </v-content>

{{--            <ul class="navbar-nav mr-auto">--}}
{{--                <li class="nav-item active">--}}
{{--                    <a class="nav-link" href="{{ route('home') }}">Home</a>--}}
{{--                </li>--}}
{{--                <li class="nav-item">--}}
{{--                    <a class="nav-link" href="{{ route('rate.index') }}">Results</a>--}}
{{--                </li>--}}
{{--            </ul>--}}
    </v-app>
</div>

<script src="{{ mix( '/js/app.js' ) }}"></script>
@stack('scripts')

</body>
</html>

resources/views/rates/index.blade.php
@extends('layouts.app')

@section('content')
    <v-row>
        <v-col cols="12">
            <data-table :columns="columns" class="table" ></data-table>
        </v-col>
    </v-row>
@endsection